on: [push]

jobs:
  build:
    name: Run Infrastructure Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install go
          npm install terraform
      - name: Run tests
        run: |
          cd test
          go test -v -timeout 30m