on: [push]

jobs:
  build:
    name: Run Infrastructure Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install go
          npm install terraform
      - name: Run tests
        run: |
          echo $AWS_ACCESS_KEY_ID
          cd test
          go test -v -timeout 30m
        env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
